### ISSUE TITLE
Considerações importantes sobre a modelagem

### ISSUE THREAD

**Issue by bmarchete** [RainbowGuys/projeto-vestido#4]
@RainbowGuys 
Pessoal, seguem algumas considerações importantes sobre sua modelagem:

1. O cliente só pode comprar ou alugar um vestido por vez?
2. Se o preço do vestido mudar, o histórico da compra vai ter o seu preço alterado também. Isto está correto?
3. A comissão do funcionário é um valor fixo? Comissão não é baseada em vendas?
4. Como pode ser feito o cálculo do lucro se o valor da venda não fica registrado em lugar nenhum?

Acho que sem organizar essas questões, vai ficar difícil do outro grupo ajudar!

**Comment by RainbowGuys** [comment]
Muito obrigada pelas considerações. Estaremos esclarecendo suas dúvidas na sequência...

1. Sim, cada compra ou aluguel só pode conter um produto cadastrado por vez;
2. Iremos encontrar um meio de resolver este problema, obrigada;
3.Sim, a comissão é um valor fixo de R$5,00 por venda, o valor deve ser multiplicado pela quantidade de vendas em que o id do funcionário aparece.
4.Como cada venda possui apenas um produto, o lucro da venda será equivalente ao valor do mesmo.
Espero ter ajudado e  obrigada pelo feedback.

**Comment by bmarchete** [comment]
Acredito que ajudou sim, levem isso em consideração @Cinema-Etim
